# Generated by Django 4.2.6 on 2023-12-30 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_orderitem_product_order_selected_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='selected_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.address'),
        ),
    ]
